# Change these first
owner: devishke-orange # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: OrangeHRM Starter Demo
    url: https://opensource-demo.orangehrmlive.com

status-website:
  baseUrl: /upptime
  logoUrl: https://orangehrm.com/_resources/themes/orangehrm/dist/images/OrangeHRM_Logo.svg
  name: OrangeHRM
  introTitle: "The **OrangeHRM Starter Demo** allows users to experiment with all the features of OrangeHRM Starter without restriction."
  introMessage: This status page uses Upptime to monitor the status of the live demo site.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
